config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController


  def index
    @flats = Flat.all
  end





end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/index.html.erb
<br>
<br>
<br>
<h1>All our Flats</h1>

<p>All 5 flats</p>

<div .card>
  <ul>
    <% @flats.each do |flat| %>
      <li><%= link_to(flat.name, flat_path(flat)) %>
      <%= link_to "Delete",
              flat_path(flat),
              method: :delete,
              data: { confirm: "Are you sure?" } %></p>
      </li>
    <% end %>
  </ul>
</div>

<%= link_to "Create",  new_flat_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="/">Simple Airbnb</a>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <div class="ms-auto flex">
            <form class="flex my-2 my-lg-0">
              <input class="form-control me-2" name="query" type="search" placeholder="Search" aria-label="Search" value="">
              <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
            <a class="btn btn-outline-primary my-2 my-sm-0 ms-2" href="/flats/new">Add Flat</a>
          </div>
        </div>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>